### ISSUE TITLE
可以提供数据库的表结构吗？

### ISSUE THREAD

**Issue by theNebuchadnezzar** [dtm-labs/dtmcli-java-sample#17]
看了Java、Go、Python语言的demo，

都没看到示例程序的表结构相关内容

在dtm 里找到 https://github.com/dtm-labs/dtm/blob/main/sqls/busi.mysql.sql

一段sql，发现也不对

可以提供一下可用的表结构吗？

**Comment by yedf2** [comment]
表结构是对的呢？哪里不对，帮忙指出

**Comment by theNebuchadnezzar** [comment]
首先在本地库执行了  https://github.com/dtm-labs/dtm/blob/main/sqls/busi.mysql.sql 这段sql

然后java sample里

1.application.yml 文件使用的库名：
```
  datasource:
    url: jdbc:mysql://localhost:3306/dtm_barrier?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
```
把‘dtm_barrier’改为‘dtm_busi’了

2.代码 TransBarrierController.java : 169 中使用的SQL语句：
```
            String sql = "update dtm_busi.user_account set trading_balance=trading_balance-?,balance=balance+? where user_id=?";

```

运行 DtmcliJavaSampleApplication.java ，执行 curl localhost:8081/api/tccBarrier 有报错

```
2022-04-18 14:47:23.109  INFO 5216 --- [nio-8081-exec-4] c.d.j.s.c.TransBarrierController         : barrierTransOutCancel branchBarrier:BranchBarrier(transType=tcc, gid=Kuc8HRtDR9Q4oQHUkV5JxD, branchId=01, op=cancel, barrierId=0)
2022-04-18 14:47:23.134  WARN 5216 --- [nio-8081-exec-4] barrier.BranchBarrier                    : barrier call error

java.sql.SQLSyntaxErrorException: Table 'dtm_busi.barrier' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.26.jar:8.0.26]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.26.jar:8.0.26]

```


java demo代码里用到的表，在sql文件里名字没对上

**Comment by theNebuchadnezzar** [comment]
又找到一段建 barrier 表的sql，https://github.com/dtm-labs/dtm/blob/main/sqls/dtmcli.barrier.mysql.sql

执行完代码能用了

建议在readme加上说明以及两个sql的链接
